### ISSUE TITLE
/list setup

### ISSUE THREAD

**Issue by DarpyDarpan** [interceptic/SkyblockValueParser#1]
When I try to list an acc by using /list , it asks me to setup , everything goes well including account category id and seller role id but when it asks for profile category id   even if I out the correct id , it gives me an error.
![Screenshot_20240622_121340_Discord](https://github.com/interceptic/SkyblockValueParser/assets/143954009/6e852221-3e67-4187-ac22-f347dde95279)

**Comment by interceptic** [comment]
fixed
